# @package _group_
name_of_run: test_config
filename: C:\Users\Igor\PycharmProjects\id-gnn\ggnn_model.pkl.gz
use_checkpoint: True
restore_path: C:\Users\Igor\PycharmProjects\id-gnn\ggnn_model.pkl.gz
parallelize: True
use_multiprocessing: False
validate_on_start: False

max_epochs: 10
dropout: 0.1
max_lr: 1e-3
minibatch_size: 8
gpus: 1
# if use_checkpoint == True next parameters will be loaded from checkpoint
mp_type: ggnn
hidden_state_size: 64
max_nodes_per_graph: 100000
max_graph_edges: 500000,
stop_extending_minibatch_after_num_nodes: 200000
