# @package _group_
name_of_run: test_config
filename: C:\Users\Igor\PycharmProjects\id-gnn\ggnn_model.pkl.gz
use_checkpoint: True
restore_path: C:\Users\Igor\PycharmProjects\id-gnn\ggnn_model.pkl.gz
parallelize: True
use_multiprocessing: False

max_epochs: 10
mp_type: ggnn
hidden_state_size: 64
dropout: 0.1
max_lr: 1e-3
minibatch_size: 128
gpus: 1
