# @package _group_
name_of_run: test_config
filename: C:\Users\Igor\PycharmProjects\id-gnn\test_model.pkl.gz
restore_path:
#  C:\Users\Igor\PycharmProjects\id-gnn\test_model.pkl.gz
parallelize: True
use_multiprocessing: False

max_epochs: 10
mp_type: ggnn
hidden_state_size: 16
dropout: 0.1
max_lr: 1e-3
minibatch_size: 8
gpus: 1
